db:
    url:
        docker: mongodb://yourusername:yourpassword@segfaultapi-db:27017
        local: mongodb://yourusername:yourpassword@0.0.0.0:27017

app:
    port: 6893
    hcaptcha:
        secret: "yourhcaptchasecret" # must be in quotes
        sitekey: yourhcaptchasitekey
    webhook: yourdiscordwebhookurl
    state:
        announcements: true
        form: true
        status: true
        blog: true
